# Generated by Django 5.0 on 2023-12-17 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='adopter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adoptation.adopter'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='adopter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adoptation.adopter'),
        ),
    ]
