# Generated by Django 5.0 on 2023-12-19 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptation', '0002_alter_cat_adopter_alter_dog_adopter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='adopter',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='age',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='adopter',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='age',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='name',
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=1)),
                ('adopter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adoptation.adopter')),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='animal_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adoptation.animal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='animal_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adoptation.animal'),
            preserve_default=False,
        ),
    ]
